FROM resin/armv7hf-debian-qemu

RUN [ "cross-build-start" ]

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install ca-certificates

RUN mkdir -p /go
ADD . /go

WORKDIR /go

CMD ["/go/av-api"]

EXPOSE 8000

RUN [ "cross-build-end" ]
