FROM arm32v7/alpine:3.18
LABEL maintainer="Daniel Randall <danny_randall@byu.edu>"

ARG NAME

COPY ${NAME} /av-api
COPY version.txt version.txt

# add any required files/folders here

ENTRYPOINT ["/av-api"]
