FROM arm32v7/debian:stable-slim
MAINTAINER Daniel Randall <danny_randall@byu.edu>

#RUN apt-get update && apt-get -y install PACKAGES && apt-clean --aggressive

ARG NAME
ENV name=${NAME}

COPY ${name}-arm ${name}-arm
COPY version.txt version.txt

# add any required files/folders here

# ENTRYPOINT ./${name}-arm
ENTRYPOINT ["./av-api-arm"]
