package state

import (
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"strings"
	"sync"
	"time"

	"github.com/byuoitav/authmiddleware/bearertoken"
	"github.com/byuoitav/av-api/base"
	se "github.com/byuoitav/av-api/statusevaluators"
	"github.com/byuoitav/configuration-database-microservice/structs"
	"github.com/byuoitav/event-router-microservice/eventinfrastructure"
)

const TIMEOUT = 5

//builds a Status object corresponding to a device and writes it to the channel
func issueCommands(commands []se.StatusCommand, channel chan []se.StatusResponse, control *sync.WaitGroup) {

	log.Printf("Issuing commands...\n\n")

	//final output
	outputs := []se.StatusResponse{}

	//iterate over list of StatusCommands
	//TODO:make sure devices can handle rapid-fire API requests
	for _, command := range commands {

		log.Printf("Command: %s against device %s, destination device: %s, parameters: %v", command.Action.Name, command.Device.Name, command.DestinationDevice.Device.Name, command.Parameters)

		output := se.StatusResponse{
			Generator:         command.Generator,
			SourceDevice:      command.Device,
			DestinationDevice: command.DestinationDevice,
		}
		statusResponseMap := make(map[string]interface{})

		//build url
		url := command.Action.Microservice + command.Action.Endpoint.Path
		for formal, actual := range command.Parameters {

			log.Printf("Formal: %s, actual: %s", formal, actual)

			toReplace := ":" + formal
			if !strings.Contains(url, toReplace) {
				errorMessage := "Could not find parameter " + toReplace + " issuing the command " + command.Action.Name
				output.ErrorMessage = &errorMessage
				outputs = append(outputs, output)
				log.Printf(errorMessage)
			} else {
				url = strings.Replace(url, toReplace, actual, -1)
			}
		}

		log.Printf("Sending requqest to %s", url)
		timeout := time.Duration(TIMEOUT * time.Second)
		client := http.Client{
			Timeout: timeout,
		}
		response, err := client.Get(url)
		if err != nil {
			errorMessage := err.Error()
			output.ErrorMessage = &errorMessage
			outputs = append(outputs, output)
			log.Printf("Error getting response from %s", command.Device.Name)
			continue
		}
		defer response.Body.Close()

		body, err := ioutil.ReadAll(response.Body)
		if err != nil {
			errorMessage := err.Error()
			output.ErrorMessage = &errorMessage
			outputs = append(outputs, output)
			log.Printf("Error reading response from %s", command.Device.Name)
			continue
		}

		//check to see if it returned a non 200 response, if so, we need to build the error.
		if response.StatusCode != 200 {
			log.Printf("Non 200 recieved: logging. Message recieved: %s", body)
			errorMessage := "Error with the request: %v" + string(body)
			base.PublishError(errorMessage, eventinfrastructure.AUTOGENERATED)
			continue
		}

		log.Printf("microservice returned: %s", body)

		var status map[string]interface{}
		err = json.Unmarshal(body, &status)
		if err != nil {
			errorMessage := "microservice returned: " + string(body)
			output.ErrorMessage = &errorMessage
			outputs = append(outputs, output)
			log.Printf("Error unmarshalling response from %s", command.Device.Name)
			continue
		}

		log.Printf("Copying data into output")
		for device, object := range status {
			statusResponseMap[device] = object
			log.Printf("%s maps to %v", device, object)
		}

		output.Status = statusResponseMap
		//add the full status response
		outputs = append(outputs, output)
	}

	//write output to channel
	log.Printf("Writing output to channel...")
	for _, output := range outputs {
		log.Printf("outputs from device %v", output.SourceDevice.GetFullName())
		for key, value := range output.Status {
			log.Printf("%s maps to %v", key, value)
		}
	}

	channel <- outputs
	log.Printf("Done acquiring statuses from  %s", commands[0].Device.GetFullName())
	control.Done()
}

func processAudioDevice(device se.Status) (base.AudioDevice, error) {

	log.Printf("Adding audio device: %s", device.DestinationDevice.Name)
	log.Printf("Status map: %v", device.Status)

	var audioDevice base.AudioDevice

	muted, ok := device.Status["muted"]
	mutedBool, ok := muted.(bool)
	if ok {
		audioDevice.Muted = &mutedBool
	}

	volume, ok := device.Status["volume"]
	if ok {
		//Default unmarshals to a float 64 - so we have to coerce it to an int
		var volumeInt int
		if volFloat, ok := volume.(float64); ok {
			volumeInt = int(volFloat)
		} else {
			volumeInt, ok = volume.(int)
		}

		//volumeint should be set now
		if ok {
			audioDevice.Volume = &volumeInt
		} else {
			log.Printf("Volume type assertion failed for %v", volume)
		}
	}

	power, ok := device.Status["power"]
	powerString, ok := power.(string)
	if ok {
		audioDevice.Power = powerString
	}

	input, ok := device.Status["input"]
	inputString, ok := input.(string)
	if ok {
		audioDevice.Input = inputString
	}

	audioDevice.Name = device.DestinationDevice.Name
	return audioDevice, nil
}

func processDisplay(device se.Status) (base.Display, error) {

	log.Printf("Adding display: %s", device.DestinationDevice.Name)

	var display base.Display

	blanked, ok := device.Status["blanked"]
	blankedBool, ok := blanked.(bool)
	if ok {
		display.Blanked = &blankedBool
	}

	power, ok := device.Status["power"]
	powerString, ok := power.(string)
	if ok {
		display.Power = powerString
	}

	input, ok := device.Status["input"]
	inputString, ok := input.(string)
	if ok {
		display.Input = inputString
	}

	display.Name = device.DestinationDevice.Name

	return display, nil
}

//make a GET request given a microservice and endpoint and publishes the results
//returns the state the microservice reports or nothing if the microservice doesn't respond
//publishes a state event or an error
//@pre the parameters have been filled, e.g. the endpoint does not contain ":"
func ExecuteCommand(action base.ActionStructure, command structs.Command, endpoint string) interface{} {

	log.Printf("Sending request to %s%s...", command.Microservice, endpoint)

	client := &http.Client{
		Timeout: TIMEOUT * time.Second,
	}
	req, err := http.NewRequest("GET", command.Microservice+endpoint, nil)
	if err != nil {
		return nil
	}

	if len(os.Getenv("LOCAL_ENVIRONMENT")) == 0 {
		token, err := bearertoken.GetToken()
		if err != nil {
			return nil
		}
		req.Header.Set("Authorization", "Bearer "+token.Token)
	}

	resp, err := client.Do(req)
	defer resp.Body.Close()

	//if error, record it
	if err != nil {

		errorMessage := fmt.Sprintf("Problem sending request: %s", err.Error())
		log.Printf(errorMessage)
		PublishError(errorMessage, action)
		return nil

	} else if resp.StatusCode != 200 { //check the response code, if non-200, we need to record and report

		log.Printf("[error] non-200 response code: %s", resp.StatusCode)

		b, err := ioutil.ReadAll(resp.Body)
		if err != nil {

			log.Printf("Problem reading the response: %v", err.Error())
			PublishError(err.Error(), action)
		}

		log.Printf("microservice returned: %v", b)
		PublishError(fmt.Sprintf("%s", b), action)

		return nil

	} else {

		//TODO: we need to find some way to check against the correct response value, just as a further validation

		for _, event := range action.EventLog {

			base.SendEvent(
				event.Type,
				event.EventCause,
				event.Device,
				action.Device.Room.Name,
				action.Device.Building.Shortname,
				event.EventInfoKey,
				event.EventInfoValue,
				false,
			)
		}

		log.Printf("Successfully sent command %s to device %s.", action.Action, action.Device.Name)
		//unmarshal status
		return resp.Body

	}

}

/*
ReplaceIPAddressEndpoint is a simple helper
*/
func ReplaceIPAddressEndpoint(path string, address string) string {
	//magic strings
	toReplace := ":address"

	return strings.Replace(path, toReplace, address, -1)

}

//@pre the endpoint's IP parameter has already been replaced
//replaces parameters in the command endpoint
//@post the endpoint does not contain ':'
func ReplaceParameters(endpoint string, parameters map[string]string) (string, error) {

	log.Printf("Replacing formal parameters with actual parameters...")

	for k, v := range parameters {
		toReplace := ":" + k
		if !strings.Contains(endpoint, toReplace) {
			errorString := "parameter not found"
			log.Printf(errorString)
			return "", errors.New(errorString)
		}

		endpoint = strings.Replace(endpoint, toReplace, v, -1)
	}

	if strings.Contains(endpoint, ":") {
		errorString := "not enough parameters provided for command"
		log.Printf(errorString)
		return "", errors.New(errorString)
	}

	return endpoint, nil
}

func PublishError(message string, action base.ActionStructure) {

	log.Printf("Publishing error: %s...", message)
	base.SendEvent(
		eventinfrastructure.ERROR,
		eventinfrastructure.USERINPUT,
		action.Device.GetFullName(),
		action.Device.Room.Name,
		action.Device.Building.Shortname,
		action.Action,
		message,
		true)

}
